import { ArrowBigLeftIcon } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import DashboardNav from "./dashboardComponents/DashboardNav";
import NavLink from "./dashboardComponents/NavLink";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by XXX",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const NavItems = [
    {
      name: "Dashboard",
      href: "/dashboard",
    },
    {
      name: "Users",
      href: "/dashboard/users",
    },
    {
      name: "Add Notice",
      href: "/dashboard/notice",
    },
    {
      name: "Upload-Pdf",
      href: "/dashboard/upload-pdfs",
    },
    {
      name: "Upload-photos",
      href: "/dashboard/upload-photos",
    },
    {
      name: "Upload-videos",
      href: "/dashboard/upload-videos",
    },
    {
      name: "Add-ExamDate",
      href: "/dashboard/add-examDate",
    },
    {
      name: "Add-ExamTable",
      href: "/dashboard/add-examTable",
    },
    {
      name: "Class routine",
      href: "/dashboard/classRoutineUpload",
    },
  ];

  return (
    <div className=" md:flex justify-between h-screen">
      <div className=" md:w-[15%] hidden md:block bg-white text-gray-500 border-r-2">
        <h1 className="text-center my-3 text-md font-semibold capitalize">
          items
        </h1>
        <div className="flex flex-col">
          {NavItems.map((item) => (
            <NavLink
              key={crypto.randomUUID()}
              name={item.name}
              href={item.href}
            />
          ))}

          <Link href="/" className="mt-5 text-center text-primary font-medium">
            <ArrowBigLeftIcon className="inline " />
            back to Home
          </Link>
        </div>
      </div>

      <div className=" md:hidden">
        <DashboardNav />
      </div>

      <div className=" mt-14 md:mt-0 px-2 md:w-[85%] bg-white overflow-hidden overflow-y-scroll ">
        {children}
      </div>
    </div>
  );
}
