import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by XXX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <div className=" md:flex justify-between">
  <div className="hidden md:block bg-red-50">
    sidebar
  </div>
  <div>
    {children}
  </div>
  
  </div>

   
  );
}
